#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
Leakage-controlled SHAP feature selection and nested-CV Round II analysis.

PURPOSE
-------
This script performs a leakage-controlled Round II analysis for one MUV target.
It reuses the exact outer-fold assignments generated by the Round I script
(MUV_nested_SVM.py), ensuring a paired and directly comparable evaluation.

For each outer fold:

1. The held-out outer-test fold is excluded from all model selection and SHAP steps.
2. A full-descriptor RBF-SVM is fitted on the outer-training partition using the
   fold-specific C and gamma selected during Round I.
3. SHAP importance is estimated exclusively from outer-training data.
4. The top-k descriptors are selected independently within that outer fold.
5. A reduced RBF-SVM is tuned by inner stratified three-fold cross-validation.
6. A decision threshold is optimized using inner-CV predictions generated only
   from the outer-training partition.
7. The optimized reduced model is evaluated once on the unchanged outer-test fold.
8. Fold-level metrics, OOF predictions, SHAP rankings, feature-selection stability,
   configuration metadata, and figures are saved.

LEAKAGE CONTROL
---------------
- Outer-test samples are never used for preprocessing, SHAP estimation,
  feature selection, hyperparameter tuning, threshold selection, or model fitting.
- SHAP-based feature selection is repeated independently within each outer fold.
- No oversampling, undersampling, or synthetic sample generation is performed.
- The original active/inactive distribution is retained.
- class_weight="balanced" is used during SVM training.

REQUIRED INPUTS
---------------
1. <file_stem>.xlsx
   - worksheet: MD
   - binary label column: Class
   - first column: sample identifier

2. Round I results directory containing:
   - out_of_fold_predictions.csv
   - fold_metrics_and_hyperparameters.csv

EXAMPLE
-------
python MUV_nested_SHAP_round2_final.py MUV_832 \
    --round1-dir MUV_832_nested_svm_results

OPTIONAL FASTER SETTINGS
------------------------
python MUV_nested_SHAP_round2_final.py MUV_832 \
    --round1-dir MUV_832_nested_svm_results \
    --shap-explain-samples 40 \
    --shap-background-samples 30

DEFAULT OUTPUT DIRECTORY
------------------------
<file_stem>_nested_shap_round2_results
"""

from __future__ import annotations

import argparse
import json
import sys
import time
from pathlib import Path
from typing import Any

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import shap
from sklearn.base import clone
from sklearn.feature_selection import VarianceThreshold
from sklearn.metrics import (
    accuracy_score,
    balanced_accuracy_score,
    confusion_matrix,
    f1_score,
    precision_score,
    recall_score,
    roc_auc_score,
    roc_curve,
)
from sklearn.model_selection import GridSearchCV, StratifiedKFold, cross_val_predict
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC


RANDOM_STATE = 42
INNER_FOLDS = 3
EF_FRACTION = 0.01

PARAM_GRID = {
    "svc__C": [0.1, 1.0, 10.0, 100.0],
    "svc__gamma": ["scale", 0.001, 0.01, 0.1],
}


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Leakage-controlled nested SHAP Round II analysis for MUV."
    )
    parser.add_argument(
        "file_stem",
        help="Input Excel file stem, e.g. MUV_832 for MUV_832.xlsx.",
    )
    parser.add_argument(
        "--round1-dir",
        required=True,
        help="Directory containing Round I outputs for the same target.",
    )
    parser.add_argument(
        "--sheet",
        default="MD",
        help="Excel worksheet containing descriptors and Class (default: MD).",
    )
    parser.add_argument(
        "--top-k",
        type=int,
        default=50,
        help="Number of descriptors selected independently per outer fold (default: 50).",
    )
    parser.add_argument(
        "--shap-explain-samples",
        type=int,
        default=60,
        help=(
            "Maximum number of outer-training samples explained per fold. "
            "Actives are prioritized, then inactives are sampled (default: 60)."
        ),
    )
    parser.add_argument(
        "--shap-background-samples",
        type=int,
        default=40,
        help="Maximum number of outer-training background samples (default: 40).",
    )
    parser.add_argument(
        "--output-dir",
        default=None,
        help="Default: <file_stem>_nested_shap_round2_results.",
    )
    parser.add_argument(
        "--n-jobs",
        type=int,
        default=-1,
        help="Parallel jobs for GridSearchCV/cross_val_predict (default: -1).",
    )
    return parser.parse_args()


def validate_args(args: argparse.Namespace) -> None:
    if args.top_k < 1:
        raise ValueError("--top-k must be at least 1.")
    if args.shap_explain_samples < 2:
        raise ValueError("--shap-explain-samples must be at least 2.")
    if args.shap_background_samples < 2:
        raise ValueError("--shap-background-samples must be at least 2.")


def read_data(file_path: Path, sheet_name: str) -> tuple[pd.DataFrame, pd.Series]:
    if not file_path.exists():
        raise FileNotFoundError(f"Input file not found: {file_path}")

    df = pd.read_excel(file_path, sheet_name=sheet_name, header=0, index_col=0)

    if "Class" not in df.columns:
        raise ValueError("The worksheet must contain a binary label column named 'Class'.")

    X = df.drop(columns=["Class"]).copy()
    y = df["Class"].copy()

    X = X.apply(pd.to_numeric, errors="raise")
    X.columns = X.columns.astype(str)
    X.index = X.index.astype(str)
    y.index = y.index.astype(str)

    if X.index.has_duplicates:
        raise ValueError("Sample identifiers must be unique.")
    if X.isna().any().any():
        missing_count = int(X.isna().sum().sum())
        raise ValueError(
            f"Descriptor matrix contains {missing_count} missing values. "
            "Imputation is not configured."
        )
    if y.isna().any():
        raise ValueError("The Class column contains missing values.")
    if not set(pd.unique(y)).issubset({0, 1}):
        raise ValueError(
            f"Class labels must contain only 0 and 1. Found: {sorted(pd.unique(y))}"
        )

    y = y.astype(int)

    if y.nunique() != 2:
        raise ValueError("Both classes 0 and 1 must be present.")

    return X, y


def compute_ef(
    labels: np.ndarray,
    scores: np.ndarray,
    fraction: float = EF_FRACTION,
) -> float:
    labels = np.asarray(labels, dtype=int)
    scores = np.asarray(scores, dtype=float)

    if len(labels) != len(scores):
        raise ValueError("labels and scores must have the same length.")

    active_fraction = labels.mean()
    if active_fraction <= 0:
        return np.nan

    n_top = max(1, int(np.ceil(len(labels) * fraction)))
    order = np.argsort(-scores, kind="mergesort")
    hits_top = labels[order[:n_top]].sum()

    return float((hits_top / n_top) / active_fraction)


def select_threshold_youden(y_true: np.ndarray, scores: np.ndarray) -> float:
    fpr, tpr, thresholds = roc_curve(y_true, scores)
    finite = np.isfinite(thresholds)

    if not finite.any():
        return 0.5

    valid_indices = np.where(finite)[0]
    best_local = int(np.argmax((tpr - fpr)[finite]))
    return float(thresholds[valid_indices[best_local]])


def threshold_metrics(
    y_true: np.ndarray,
    scores: np.ndarray,
    threshold: float,
) -> dict[str, float]:
    pred = (scores >= threshold).astype(int)
    tn, fp, fn, tp = confusion_matrix(y_true, pred, labels=[0, 1]).ravel()

    specificity = tn / (tn + fp) if (tn + fp) else np.nan

    return {
        "threshold": float(threshold),
        "accuracy": float(accuracy_score(y_true, pred)),
        "balanced_accuracy": float(balanced_accuracy_score(y_true, pred)),
        "precision": float(precision_score(y_true, pred, zero_division=0)),
        "recall_sensitivity": float(recall_score(y_true, pred, zero_division=0)),
        "specificity": float(specificity),
        "f1": float(f1_score(y_true, pred, zero_division=0)),
    }


def build_reduced_pipeline() -> Pipeline:
    return Pipeline(
        steps=[
            ("variance", VarianceThreshold(threshold=0.0)),
            ("scaler", StandardScaler()),
            (
                "svc",
                SVC(
                    kernel="rbf",
                    class_weight="balanced",
                    probability=True,
                    random_state=RANDOM_STATE,
                ),
            ),
        ]
    )


def class_aware_explanation_indices(
    y_train: pd.Series,
    max_samples: int,
    rng: np.random.Generator,
) -> np.ndarray:
    """
    Prioritize outer-training actives in the SHAP explanation subset, then fill
    remaining positions with randomly sampled outer-training inactives.

    This sampling affects SHAP approximation only. Model training and evaluation
    use the full original outer-training and outer-test partitions.
    """
    positive = np.flatnonzero(y_train.to_numpy() == 1)
    negative = np.flatnonzero(y_train.to_numpy() == 0)

    if len(positive) >= max_samples:
        return np.sort(rng.choice(positive, size=max_samples, replace=False))

    remaining = max_samples - len(positive)
    n_negative = min(remaining, len(negative))

    if n_negative == 0:
        return np.sort(positive)

    selected_negative = rng.choice(negative, size=n_negative, replace=False)
    return np.sort(np.concatenate([positive, selected_negative]))


def random_background_indices(
    n_rows: int,
    max_samples: int,
    rng: np.random.Generator,
) -> np.ndarray:
    size = min(n_rows, max_samples)
    return np.sort(rng.choice(np.arange(n_rows), size=size, replace=False))


def fit_full_model_for_shap(
    X_train: pd.DataFrame,
    y_train: pd.Series,
    c_value: float,
    gamma_value: Any,
) -> tuple[
    VarianceThreshold,
    StandardScaler,
    SVC,
    np.ndarray,
    np.ndarray,
]:
    """
    Fit variance filter, scaler, and probability=False SVC on outer-training data.

    probability=False is used because SHAP only needs a continuous decision function
    and probability calibration would add substantial runtime.
    """
    variance = VarianceThreshold(threshold=0.0)
    X_var = variance.fit_transform(X_train)

    retained_features = X_train.columns[variance.get_support()].to_numpy(dtype=str)

    scaler = StandardScaler()
    X_scaled = scaler.fit_transform(X_var)

    model = SVC(
        kernel="rbf",
        C=float(c_value),
        gamma=gamma_value,
        class_weight="balanced",
        probability=False,
        random_state=RANDOM_STATE,
    )
    model.fit(X_scaled, y_train)

    return variance, scaler, model, retained_features, X_scaled


def estimate_training_only_shap(
    X_train_scaled: np.ndarray,
    y_train: pd.Series,
    model: SVC,
    retained_features: np.ndarray,
    explain_samples: int,
    background_samples: int,
    seed: int,
) -> pd.DataFrame:
    rng = np.random.default_rng(seed)

    explain_idx = class_aware_explanation_indices(
        y_train=y_train,
        max_samples=explain_samples,
        rng=rng,
    )
    background_idx = random_background_indices(
        n_rows=len(X_train_scaled),
        max_samples=background_samples,
        rng=rng,
    )

    X_explain = X_train_scaled[explain_idx]
    X_background = X_train_scaled[background_idx]

    masker = shap.maskers.Independent(
        X_background,
        max_samples=len(X_background),
    )

    explainer = shap.Explainer(
        model.decision_function,
        masker,
        algorithm="permutation",
    )

    # Minimum required by permutation SHAP.
    max_evals = 2 * X_train_scaled.shape[1] + 1

    shap_values = explainer(
        X_explain,
        max_evals=max_evals,
        batch_size="auto",
        silent=False,
    )

    values = np.asarray(shap_values.values)
    if values.ndim != 2:
        raise ValueError(f"Unexpected SHAP value shape: {values.shape}")

    importance = np.mean(np.abs(values), axis=0)

    result = pd.DataFrame(
        {
            "feature": retained_features.astype(str),
            "mean_abs_shap": importance.astype(float),
        }
    ).sort_values(
        "mean_abs_shap",
        ascending=False,
        ignore_index=True,
    )

    result["rank"] = np.arange(1, len(result) + 1, dtype=int)
    result["n_explained_samples"] = int(len(explain_idx))
    result["n_background_samples"] = int(len(background_idx))
    result["n_explained_actives"] = int(y_train.iloc[explain_idx].sum())

    return result


def normalize_gamma(value: Any) -> Any:
    if isinstance(value, str):
        stripped = value.strip()
        if stripped in {"scale", "auto"}:
            return stripped
        try:
            return float(stripped)
        except ValueError:
            return stripped
    return value


def json_safe(value: Any) -> Any:
    """
    Recursively convert NumPy/pandas scalar objects into JSON-serializable values.
    """
    if isinstance(value, dict):
        return {str(k): json_safe(v) for k, v in value.items()}
    if isinstance(value, (list, tuple, set)):
        return [json_safe(v) for v in value]
    if isinstance(value, np.ndarray):
        return [json_safe(v) for v in value.tolist()]
    if isinstance(value, (np.integer,)):
        return int(value)
    if isinstance(value, (np.floating,)):
        return float(value)
    if isinstance(value, (np.bool_,)):
        return bool(value)
    if pd.isna(value):
        return None
    return value


def save_json(data: dict[str, Any], path: Path) -> None:
    with open(path, "w", encoding="utf-8") as fh:
        json.dump(json_safe(data), fh, indent=2, ensure_ascii=False)


def main() -> int:
    args = parse_args()
    validate_args(args)

    file_path = Path(f"{args.file_stem}.xlsx").resolve()
    round1_dir = Path(args.round1_dir).resolve()
    output_dir = Path(
        args.output_dir or f"{args.file_stem}_nested_shap_round2_results"
    ).resolve()
    output_dir.mkdir(parents=True, exist_ok=True)

    print(f"Input file: {file_path}")
    print(f"Round I directory: {round1_dir}")
    print(f"Output directory: {output_dir}")

    X, y = read_data(file_path, args.sheet)

    oof_round1_path = round1_dir / "out_of_fold_predictions.csv"
    fold_round1_path = round1_dir / "fold_metrics_and_hyperparameters.csv"

    if not oof_round1_path.exists() or not fold_round1_path.exists():
        raise FileNotFoundError(
            "Round I directory must contain out_of_fold_predictions.csv and "
            "fold_metrics_and_hyperparameters.csv."
        )

    round1_oof = pd.read_csv(oof_round1_path, dtype={"sample_id": str})
    round1_folds = pd.read_csv(fold_round1_path)

    required_oof = {"sample_id", "outer_fold"}
    if not required_oof.issubset(round1_oof.columns):
        raise ValueError(
            f"Round I OOF file must contain columns: {sorted(required_oof)}"
        )

    required_fold = {"outer_fold", "best_C", "best_gamma"}
    if not required_fold.issubset(round1_folds.columns):
        raise ValueError(
            f"Round I fold file must contain columns: {sorted(required_fold)}"
        )

    if round1_oof["sample_id"].duplicated().any():
        raise ValueError("Duplicate sample IDs detected in Round I OOF predictions.")

    fold_map = round1_oof.set_index("sample_id")["outer_fold"]

    missing_ids = X.index.difference(fold_map.index)
    extra_ids = fold_map.index.difference(X.index)

    if len(missing_ids) or len(extra_ids):
        raise ValueError(
            "Round I sample IDs do not match the input data. "
            f"Missing in Round I={len(missing_ids)}, extra in Round I={len(extra_ids)}"
        )

    fold_map = fold_map.reindex(X.index).astype(int)
    outer_fold_values = [int(x) for x in sorted(fold_map.unique())]

    if len(outer_fold_values) < 2:
        raise ValueError("At least two outer folds are required.")

    class_counts = y.value_counts().sort_index()
    print(
        f"Samples={len(y)} | Features={X.shape[1]} | "
        f"Class 0={class_counts.get(0, 0)} | Class 1={class_counts.get(1, 0)}"
    )
    print(f"Reused outer folds: {outer_fold_values}")
    print(
        f"SHAP settings: explain <= {args.shap_explain_samples}, "
        f"background <= {args.shap_background_samples}, top-k={args.top_k}"
    )

    fold_rows: list[dict[str, Any]] = []
    oof_rows: list[pd.DataFrame] = []
    all_importance: list[pd.DataFrame] = []
    all_selected: list[pd.DataFrame] = []

    total_start = time.perf_counter()

    for fold_number in outer_fold_values:
        fold_start = time.perf_counter()

        test_mask = fold_map.to_numpy() == fold_number
        train_mask = ~test_mask

        X_train = X.loc[train_mask]
        X_test = X.loc[test_mask]
        y_train = y.loc[train_mask]
        y_test = y.loc[test_mask]

        row_r1 = round1_folds.loc[
            round1_folds["outer_fold"].astype(int) == fold_number
        ]

        if len(row_r1) != 1:
            raise ValueError(
                f"Expected exactly one Round I hyperparameter row for fold {fold_number}; "
                f"found {len(row_r1)}."
            )

        r1_c = float(row_r1.iloc[0]["best_C"])
        r1_gamma = normalize_gamma(row_r1.iloc[0]["best_gamma"])

        print(
            f"\nOuter fold {fold_number}/{len(outer_fold_values)}"
            f"\n  Train samples={len(X_train)} | Test samples={len(X_test)}"
            f"\n  Train actives={int(y_train.sum())} | Test actives={int(y_test.sum())}"
            f"\n  Full-model SHAP parameters from Round I: "
            f"C={r1_c}, gamma={r1_gamma}"
        )

        (
            _variance,
            _scaler,
            shap_model,
            retained_features,
            X_train_scaled,
        ) = fit_full_model_for_shap(
            X_train=X_train,
            y_train=y_train,
            c_value=r1_c,
            gamma_value=r1_gamma,
        )

        shap_start = time.perf_counter()

        importance_df = estimate_training_only_shap(
            X_train_scaled=X_train_scaled,
            y_train=y_train,
            model=shap_model,
            retained_features=retained_features,
            explain_samples=args.shap_explain_samples,
            background_samples=args.shap_background_samples,
            seed=RANDOM_STATE + fold_number,
        )

        shap_elapsed = time.perf_counter() - shap_start

        importance_df.insert(0, "outer_fold", int(fold_number))
        all_importance.append(importance_df)

        available_k = min(args.top_k, len(importance_df))
        if available_k < args.top_k:
            print(
                f"  WARNING: only {available_k} non-constant features available; "
                f"requested top-k={args.top_k}."
            )

        selected_df = importance_df.head(available_k).copy()
        selected_df["selected"] = True
        all_selected.append(selected_df)

        top_features = selected_df["feature"].astype(str).tolist()

        X_train_reduced = X_train.loc[:, top_features]
        X_test_reduced = X_test.loc[:, top_features]

        inner_cv = StratifiedKFold(
            n_splits=INNER_FOLDS,
            shuffle=True,
            random_state=RANDOM_STATE + fold_number,
        )

        print(
            f"  Tuning reduced SVM on {len(top_features)} selected descriptors..."
        )

        search = GridSearchCV(
            estimator=build_reduced_pipeline(),
            param_grid=PARAM_GRID,
            scoring="roc_auc",
            cv=inner_cv,
            n_jobs=args.n_jobs,
            refit=True,
            return_train_score=False,
            error_score="raise",
            verbose=1,
        )
        search.fit(X_train_reduced, y_train)

        best_model = search.best_estimator_

        inner_scores = cross_val_predict(
            estimator=clone(best_model),
            X=X_train_reduced,
            y=y_train,
            cv=inner_cv,
            method="predict_proba",
            n_jobs=args.n_jobs,
        )[:, 1]

        threshold = select_threshold_youden(
            y_true=y_train.to_numpy(),
            scores=inner_scores,
        )

        test_scores = best_model.predict_proba(X_test_reduced)[:, 1]

        fold_auc = roc_auc_score(y_test, test_scores)
        fold_ef = compute_ef(y_test.to_numpy(), test_scores, EF_FRACTION)
        class_metrics = threshold_metrics(
            y_true=y_test.to_numpy(),
            scores=test_scores,
            threshold=threshold,
        )

        elapsed = time.perf_counter() - fold_start

        fold_rows.append(
            {
                "outer_fold": int(fold_number),
                "n_train": int(len(X_train)),
                "n_test": int(len(X_test)),
                "train_actives": int(y_train.sum()),
                "test_actives": int(y_test.sum()),
                "n_features_before_shap": int(len(retained_features)),
                "n_selected_features": int(len(top_features)),
                "roc_auc": float(fold_auc),
                "ef1_percent": float(fold_ef),
                "best_inner_roc_auc": float(search.best_score_),
                "best_C": float(search.best_params_["svc__C"]),
                "best_gamma": search.best_params_["svc__gamma"],
                "shap_runtime_seconds": float(shap_elapsed),
                "total_fold_runtime_seconds": float(elapsed),
                **class_metrics,
            }
        )

        oof_rows.append(
            pd.DataFrame(
                {
                    "sample_id": X_test.index.astype(str),
                    "outer_fold": int(fold_number),
                    "true_label": y_test.to_numpy(dtype=int),
                    "score_active": test_scores.astype(float),
                    "optimized_threshold": float(threshold),
                    "predicted_label": (test_scores >= threshold).astype(int),
                }
            )
        )

        print(
            f"  Completed fold {fold_number} | "
            f"AUC={fold_auc:.4f} | EF1%={fold_ef:.4f} | "
            f"C={search.best_params_['svc__C']} | "
            f"gamma={search.best_params_['svc__gamma']} | "
            f"threshold={threshold:.6f} | "
            f"SHAP time={shap_elapsed:.1f}s | total={elapsed:.1f}s"
        )

    total_elapsed = time.perf_counter() - total_start

    fold_df = pd.DataFrame(fold_rows)
    oof_df = pd.concat(oof_rows, ignore_index=True)
    importance_all = pd.concat(all_importance, ignore_index=True)
    selected_all = pd.concat(all_selected, ignore_index=True)

    selection_frequency = (
        selected_all.groupby("feature", as_index=False)
        .agg(
            selected_in_n_folds=("outer_fold", "nunique"),
            mean_rank=("rank", "mean"),
            mean_abs_shap=("mean_abs_shap", "mean"),
        )
    )

    selection_frequency["selection_frequency"] = (
        selection_frequency["selected_in_n_folds"] / len(outer_fold_values)
    )

    selection_frequency["feature"] = selection_frequency["feature"].astype(str)

    selection_frequency = selection_frequency.sort_values(
        ["selected_in_n_folds", "mean_abs_shap"],
        ascending=[False, False],
        ignore_index=True,
    )

    metric_cols = [
        "roc_auc",
        "ef1_percent",
        "accuracy",
        "balanced_accuracy",
        "precision",
        "recall_sensitivity",
        "specificity",
        "f1",
    ]

    summary_rows: list[dict[str, Any]] = []

    for metric in metric_cols:
        values = fold_df[metric].astype(float)
        summary_rows.append(
            {
                "metric": metric,
                "mean": float(values.mean()),
                "std": float(values.std(ddof=1)),
                "min": float(values.min()),
                "max": float(values.max()),
            }
        )

    pooled_auc = roc_auc_score(
        oof_df["true_label"],
        oof_df["score_active"],
    )
    pooled_ef = compute_ef(
        oof_df["true_label"].to_numpy(),
        oof_df["score_active"].to_numpy(),
        EF_FRACTION,
    )

    summary_rows.extend(
        [
            {
                "metric": "pooled_oof_roc_auc",
                "mean": float(pooled_auc),
                "std": np.nan,
                "min": np.nan,
                "max": np.nan,
            },
            {
                "metric": "pooled_oof_ef1_percent",
                "mean": float(pooled_ef),
                "std": np.nan,
                "min": np.nan,
                "max": np.nan,
            },
            {
                "metric": "total_runtime_seconds",
                "mean": float(total_elapsed),
                "std": np.nan,
                "min": np.nan,
                "max": np.nan,
            },
        ]
    )

    summary_df = pd.DataFrame(summary_rows)

    # Save all tabular outputs before creating optional presentation outputs.
    fold_df.to_csv(
        output_dir / "fold_metrics_and_hyperparameters.csv",
        index=False,
    )
    oof_df.to_csv(
        output_dir / "out_of_fold_predictions.csv",
        index=False,
    )
    importance_all.to_csv(
        output_dir / "shap_importance_all_folds.csv",
        index=False,
    )
    selected_all.to_csv(
        output_dir / "top_features_by_outer_fold.csv",
        index=False,
    )
    selection_frequency.to_csv(
        output_dir / "feature_selection_frequency.csv",
        index=False,
    )
    summary_df.to_csv(
        output_dir / "summary_metrics.csv",
        index=False,
    )

    configuration = {
        "input_file": str(file_path),
        "round1_directory": str(round1_dir),
        "output_directory": str(output_dir),
        "n_samples": int(X.shape[0]),
        "n_input_features": int(X.shape[1]),
        "class_0_count": int((y == 0).sum()),
        "class_1_count": int((y == 1).sum()),
        "outer_folds_reused_from_round1": [int(x) for x in outer_fold_values],
        "inner_folds": int(INNER_FOLDS),
        "random_state": int(RANDOM_STATE),
        "top_k": int(args.top_k),
        "shap_algorithm": "permutation",
        "shap_model_output": "SVC decision_function",
        "shap_scope": "outer training only",
        "shap_explain_sampling": (
            "All available outer-training actives up to the sample cap, "
            "then randomly sampled outer-training inactives."
        ),
        "shap_explain_samples_max": int(args.shap_explain_samples),
        "shap_background_samples_max": int(args.shap_background_samples),
        "reduced_model_kernel": "rbf",
        "class_weight": "balanced",
        "resampling": "none",
        "probability_for_reduced_model": True,
        "parameter_grid": PARAM_GRID,
        "threshold_method": (
            "Youden J on inner-CV predictions generated exclusively from "
            "outer-training data."
        ),
        "ef_fraction": float(EF_FRACTION),
        "primary_metrics": ["roc_auc", "ef1_percent"],
    }

    save_json(
        configuration,
        output_dir / "analysis_configuration.json",
    )

    # Feature-selection stability plot.
    top_plot = selection_frequency.head(25).sort_values(
        ["selected_in_n_folds", "mean_abs_shap"],
        ascending=True,
    ).copy()

    top_plot["feature"] = top_plot["feature"].astype(str)

    plt.figure(figsize=(10, 8))
    plt.barh(
        top_plot["feature"],
        top_plot["selected_in_n_folds"],
    )
    plt.xlabel("Number of outer folds in which the descriptor was selected")
    plt.ylabel("Descriptor")
    plt.title(f"Top descriptor-selection stability — {args.file_stem}")
    plt.tight_layout()
    plt.savefig(
        output_dir / "top25_selection_stability.png",
        dpi=300,
        bbox_inches="tight",
    )
    plt.close()

    print("\nCompleted successfully.")
    print(
        f"Mean outer-fold ROC-AUC: "
        f"{fold_df['roc_auc'].mean():.4f} ± "
        f"{fold_df['roc_auc'].std(ddof=1):.4f}"
    )
    print(
        f"Mean outer-fold EF1%: "
        f"{fold_df['ef1_percent'].mean():.4f} ± "
        f"{fold_df['ef1_percent'].std(ddof=1):.4f}"
    )
    print(f"Pooled OOF ROC-AUC: {pooled_auc:.4f}")
    print(f"Pooled OOF EF1%: {pooled_ef:.4f}")
    print(f"Total runtime: {total_elapsed:.1f} seconds")
    print(f"Results saved in: {output_dir}")

    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except Exception as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        raise
